"""Roll up results/*.json into results/RESULTS.md (compact tables)."""

from __future__ import annotations

import json
from pathlib import Path

RESULTS = Path(__file__).resolve().parent.parent / "results"


def load(name: str):
    p = RESULTS / name
    return json.loads(p.read_text()) if p.exists() else None


def main() -> None:
    e1 = load("e1_langevin_vs_sm.json")
    e2 = load("e2_cd_bias.json")
    e3 = load("e3_parallel_chains.json")
    e4 = load("e4_cd_weighting.json")
    e5 = load("e5_partition_ais.json")
    cc = load("crosscheck_codex/codex_e2e4.json")

    L = ["# Experiment 10 — Results (MCMC / Contrastive Divergence / Z)",
         "",
         "Auto-generated by `src/make_report.py` from `results/*.json`. "
         "See `ANSWERS.md` for the prose answers to all 9 questions and "
         "`README.md` for the map.",
         ""]

    if e1:
        m = e1["mmd2"]; pr = e1["precision_recall"]
        L += ["## E1 — Continuous EBM without Z (RQ1, RQ2, Q3, Q5)",
              "",
              f"Target `{e1['meta']['dataset']}`, MLP energy, "
              f"{e1['meta']['steps']} steps on `{e1['meta']['device']}`. "
              "`Z` was never computed.",
              "",
              "| method | MCMC in training? | MMD² to data ↓ | precision | recall |",
              "| --- | --- | ---: | ---: | ---: |",
              f"| data vs data (floor) | — | {m['floor_data_vs_data']:.4f} | 1.00 | 1.00 |",
              f"| **PCD-Langevin** | yes | {m['pcd_langevin']:.4f} | "
              f"{pr['pcd_langevin']['precision']:.2f} | {pr['pcd_langevin']['recall']:.2f} |",
              f"| **score matching (DSM)** | **no** | {m['dsm_mcmc_free']:.4f} | "
              f"{pr['dsm_mcmc_free']['precision']:.2f} | {pr['dsm_mcmc_free']['recall']:.2f} |",
              f"| uniform noise (ceiling) | — | {m['ceiling_noise']:.4f} | — | — |",
              "",
              "![e1](e1_langevin_vs_sm.png)",
              ""]

    if e2:
        L += ["## E2 — Short-run CD is *biased*, not just noisy (Q6, Q7)",
              "",
              "Tiny RBM, exact MLE gradient by enumeration; `eval` model ≠ data "
              "(CD bias vanishes at the data params). Bias falls monotonically "
              "with `k`; at small `k` it dominates the MSE.",
              "",
              "| estimator | rel. bias ↓ | cosine to g* | variance | MSE |",
              "| --- | ---: | ---: | ---: | ---: |"]
        for k in ["1", "2", "5", "10", "20", "50"]:
            s = e2["e2"][k]
            L.append(f"| CD-{k} | {s['bias_rel']:.4f} | {s['cosine']:.4f} | "
                     f"{s['var']:.3f} | {s['mse']:.3f} |")
        s = e2["e2"]["pcd"]
        L += [f"| **PCD** (1 step/iter) | {s['bias_rel']:.4f} | {s['cosine']:.4f} | "
              f"{s['var']:.3f} | {s['mse']:.3f} |",
              "",
              "![e2](e2_cd_bias.png)",
              ""]

    if e4:
        L += ["## E4 — Trajectory-weighted CD: late-weighting wins (Q8, Q9)",
              "",
              "Same RBM, `K=20` Gibbs steps, equal compute. A weighted negative "
              "phase `Σ_t w_t·stats(v^(t))`. **Late-weighted averaging keeps "
              "CD-K's low bias but halves the variance → ~2× lower gradient "
              "MSE than vanilla last-only CD.**",
              "",
              "| schedule | rel. bias ↓ | variance ↓ | gradient MSE ↓ |",
              "| --- | ---: | ---: | ---: |"]
        pa = e4["part_a_gradient"]
        for name in sorted(pa, key=lambda n: pa[n]["mse"]):
            s = pa[name]
            tag = "**" if name in ("zipf_late", "geom_late") else ""
            L.append(f"| {tag}{name}{tag} | {s['bias_rel']:.4f} | "
                     f"{s['var']:.4f} | {s['mse']:.4f} |")
        pb = e4["part_b_training"]
        L += ["",
              f"End-task (exact NLL after training; data-RBM NLL "
              f"= {e4['meta']['nll_data']:.3f}): "
              + ", ".join(f"{n}={pb[n]['final_nll']:.4f}"
                          for n in sorted(pb, key=lambda n: pb[n]['final_nll'])),
              "",
              "![e4](e4_cd_weighting.png)",
              ""]

    if cc and e2:
        L += ["### Independent cross-check (Codex, from-scratch numpy)",
              "",
              "Two independent implementations agree to ~2–3 significant figures:",
              "",
              "| quantity | this impl | Codex impl |",
              "| --- | ---: | ---: |",
              f"| CD-1 rel. bias | {e2['e2']['1']['bias_rel']:.4f} | "
              f"{cc['e2']['1']['bias_rel']:.4f} |",
              f"| PCD rel. bias | {e2['e2']['pcd']['bias_rel']:.4f} | "
              f"{cc['e2']['pcd']['bias_rel']:.4f} |",
              f"| E4 best schedule | zipf_late | "
              f"{min(cc['e4'], key=lambda n: cc['e4'][n]['mse'])} |",
              f"| E4 zipf_late MSE | {e4['part_a_gradient']['zipf_late']['mse']:.4f} | "
              f"{cc['e4']['zipf_late']['mse']:.4f} |",
              ""]

    if e3:
        a = e3["part_a_ess"]; tp = e3["part_c_throughput"]["ebm_langevin_torch"]
        b = e3["part_b_coverage"]
        L += ["## E3 — Parallel / persistent chains beat one long chain (Q4, Q9)",
              "",
              f"One long Langevin chain on a 3-mode mixture is stuck: "
              f"τ={a['tau']:.0f}, only {a['ess_frac']*100:.1f}% of samples are "
              f"effective, single-chain mode weights "
              f"`{a['single_chain_weights']}` vs true `[0.33, 0.33, 0.33]`.",
              "",
              "Mode-weight error (TV) vs #chains at fixed total samples:",
              "",
              "| # chains M | TV error ↓ |",
              "| --- | ---: |"]
        for mk in b:
            L.append(f"| {mk} | {b[mk]['tv_mean']:.3f} ± {b[mk]['tv_std']:.3f} |")
        L += ["",
              f"Batched Langevin throughput on `{e3['part_c_throughput']['device']}` "
              "(near-flat ms/step ⇒ parallel chains ≈ free):",
              "",
              "| # chains | ms / step | samples / s |",
              "| --- | ---: | ---: |"]
        for mk, d in tp.items():
            L.append(f"| {mk} | {d['sec_per_step']*1e3:.2f} | "
                     f"{d['samples_per_sec']:.2e} |")
        L += ["", "![e3](e3_parallel_chains.png)", ""]

    if e5:
        a = e5["part_a_enumeration"]; b = e5["part_b_ais"]
        L += ["## E5 — Z is exponential but only needed for likelihood (RQ1, Q6)",
              "",
              f"Exact `log Z` by enumeration scales as `2^nv` "
              f"(fit slope {a['fit_slope_per_bit']:.3f} decades/bit ≈ ×2/bit). "
              f"Extrapolated: nv=50 → {a['extrapolated_sec']['50']:.1e}s, "
              f"nv=100 → {a['extrapolated_sec']['100']:.1e}s.",
              "",
              f"AIS (the messy bypass) converges to exact `log Z` "
              f"= {b['exact_logZ']:.2f}:",
              "",
              "| # AIS levels | log Z est | |error| |",
              "| --- | ---: | ---: |"]
        for r in b["runs"]:
            L.append(f"| {r['n_levels']} | {r['mean']:.3f} ± {r['std']:.3f} | "
                     f"{r['abs_err']:.4f} |")
        zf = e5["z_needed_for"]
        L += ["",
              "`Z` is needed for: "
              + ", ".join(k for k, v in zf.items() if v) + ".",
              "`Z` is NOT needed for: "
              + ", ".join(k for k, v in zf.items() if not v) + ".",
              "",
              "![e5](e5_partition_ais.png)",
              ""]

    (RESULTS / "RESULTS.md").write_text("\n".join(L))
    print(f"wrote {RESULTS / 'RESULTS.md'}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
