#!/usr/bin/env python3
"""Elyas's abstract (2026-09-10), verbatim except: 'Claude 3.5 Haiku' -> 'Claude Haiku 4.5' (factual), '%' escaped. .bak_sep10 backup."""
import os, shutil, sys
ROOT = sys.argv[1] if len(sys.argv) > 1 else "."
NEW = r"""When a language model continues a chain of reasoning that contains a false step, does it catch the error or compound it? We investigate this dynamic by evaluating models without explicit self-correction instructions. In our setup, a model solves a short program step-by-step; we then inject a false value into its trace and measure the continuation's accuracy by re-executing the program. We find that a single property dictates the outcome: whether the error is ``readable'' (contradicting a value explicitly written earlier in the trace) or ``computed'' (requiring the model to re-execute a prior operation). Across 13 models from five developers, strong models reject readable falsehoods in at least 99\% of cases. Conversely, computed falsehoods are absorbed in 88\% to 100\% of continuations by every model capable of solving the base task. While the ability to verify readable errors scales sharply with model quality, recomputation checks do not improve at all. For Claude Haiku 4.5, the boundary is absolute: absorption jumps from 2\% to 100\% as soon as a single operation separates the model from the truth. This failure mode is highly robust; showing operands beside the false value, disclosing the trace's authorship, and utilizing escalating verification instructions all fail to reduce error absorption. Furthermore, test-time reasoning clears readable errors but only marginally mitigates the deepest computed errors. Modern agent pipelines and chain-of-thought monitors assume that intermediate errors have some probability of downstream detection; our results demonstrate that for committed computed values, that probability is effectively zero."""
p = os.path.join(ROOT, "sections/00_abstract.tex"); s = open(p).read()
i = s.index("\\begin{abstract}") + len("\\begin{abstract}"); j = s.index("\\end{abstract}")
out = s[:i] + "\n" + NEW + "\n" + s[j:]
if "--dry" in sys.argv: print("ok, would write", len(NEW.split()), "words"); sys.exit(0)
shutil.copy2(p, p + ".bak_sep10"); open(p, "w").write(out); print("wrote abstract,", len(NEW.split()), "words")
